"""add column data to user, event and position

Revision ID: a81ac85b0fdc
Revises: b832a063d204
Create Date: 2023-06-06 19:17:25.144286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81ac85b0fdc'
down_revision = 'b832a063d204'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
