"""added seed data script

Revision ID: b7c5c5974fc4
Revises: a81ac85b0fdc
Create Date: 2023-06-06 20:25:46.179778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c5c5974fc4'
down_revision = 'a81ac85b0fdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
